#ifndef BASE_NTIOS_BEEP_CONFIG_H_
#define BASE_NTIOS_BEEP_CONFIG_H_


#define NUM_BEEP_SEQNO_MAX 255
#define NUM_BEEP_UPDATEQUEUE_MAX 255
#define BEEP_DUTY_CYCLE_PERC_50 50
#define BEEP_DUTY_CYCLE_PERC_MIN 0
#define BEEP_DUTY_CYCLE_PERC_MAX 100
#define BEEP_FREQ_350K 350000
#define BEEP_FREQ_MIN 1265
#define BEEP_PWM_CHANNEL 0
#define BEEP_SPEED_20 20 /* Wait for 20 cycles */
#define BEEP_USES_FREQUENCY 1



#endif  // BASE_NTIOS_CONFIG_H_