#ifndef BASE_NTIOS_BEEP_CONFIG_H_
#define BASE_NTIOS_BEEP_CONFIG_H_

#define BEEP_DUTY_CYCLE_PERC_50 50
#define BEEP_DUTY_CYCLE_PERC_MIN 0
#define BEEP_DUTY_CYCLE_PERC_MAX 100
#define BEEP_FREQ_DEFAULT 3000
#define BEEP_FREQ_MIN 300
#define BEEP_FREQ_MAX 20000
#define BEEP_PWM_CHANNEL 0
#define BEEP_SPEED_20 20 /* Wait for 20 cycles */

#endif  // BASE_NTIOS_CONFIG_H_